### ISSUE TITLE
ESLint Integration

### ISSUE THREAD

**Issue by aakankshabhende** [ente-io/photos-web#1525]
ESLint Integration to format code, to fix spacing issues and code styles.

**Comment by pushkar8723** [comment]
I didn't get what is the issue here as there is an `eslint` configured already for photos and auth apps.

https://github.com/ente-io/photos-web/blob/d9a2d3ee3906262402574d46ab56d0dc8bc3a29f/apps/photos/.eslintrc.js#L1-L13

https://github.com/ente-io/photos-web/blob/d9a2d3ee3906262402574d46ab56d0dc8bc3a29f/apps/auth/.eslintrc.js#L1-L13

Both of these extend `eslint-config` package which has basic eslint rules configured.
https://github.com/ente-io/photos-web/blob/d9a2d3ee3906262402574d46ab56d0dc8bc3a29f/packages/eslint-config/index.js#L2-L8

Do you want it to be more restrictive, like by extending [airbnb-eslint](https://www.npmjs.com/package/eslint-config-airbnb)?
Or do you want a `.vscode` settings file to auto-format on save?

**Comment by aakankshabhende** [comment]
Yes, I meant a .vscode setting to auto format.

**Comment by pushkar8723** [comment]
@abhinavkgrd Although #1527 introduces auto-format on save, we should also review the rules. Things like using `"` or `'`, and having `;` at the end of the line are not enforced.

**Comment by aakankshabhende** [comment]
@pushkar8723 @abhinavkgrd I would like to work on this issue. Could you please assign me this?
